INSERT INTO categories(id,category_name,category_name_khmer,category_parent,category_image ) VALUES
(1,'Phone & Tablets','ទូរស័ព្ទ និង Tablets',null,null),
(2,'Computers & Accessories','កុំព្យូទ័រ និង គ្រឿងបន្លាស់',null,null),
(3,'Electronics & Appliances','អេឡិចត្រូនិច និង គ្រឿងប្រើប្រាស់',null,null),
(4,'Cars and Vehicles','រថយន្ត និង យានយន្ត',null,null),
(5,'House & Lands','ផ្ទះ និង ដី',null,null),
(6,'Fashion & Beauty','សម្លៀកបំពាក់',null,null),
(7,'Books,Sports & Other','សៀវភៅ សំភារះកីឡា និង ផ្សេងៗ',null,null),
(8,'Furniture & Decor','គ្រឿងសង្ហារឹម និង ដេគ័រ',null,null);

INSERT INTO categories(category_name,category_name_khmer,category_parent,category_image ) VALUES
('Phones','ទូរស័ព្ទ',1,null),
('Tablets','Tablets',1,null),
('Phone Accessories','គ្រឿងបន្លាស់ទូរស័ព្ទ',1,null),
('Phone Numbers','លេខទូរស័ព្ទ',1,null),
('Computers','កុំព្យូទ័រ',2,null),
('Computer accessories','គ្រឿងកុំព្យូទ័រ',2,null),
('Softwares','កម្មវិធី',2,null),
('Consumer Electronics','ឧបករណ៍អេឡិចត្រូនិក',3,null),
('Security Camera','កាមេរ៉ាសុវត្ថិភាព',3,null),
('Cameras,camcorders','ម៉ាស៊ីនថត និង កាមេរ៉ា',3,null),
('TVs,Videos and Audios','ទូរទស្សន៍ គ្រឿងបំពងសំឡេង និង វីដេអូ',3,null),
('Home appliances ','ប្រដាប់ប្រើប្រាស់ក្នុងផ្ទះ',3,null),
('Video games,consoles,toys','ឧបគរណ៍ហ្គេម និង ឧបករណ៍ក្មេងលេង',3,null),
('Cars','រថយន្ត',4,null),
('Motorcycles','ម៉ូតូ',4,null),
('Car Parts & Accessories','គ្រឿងបន្លាស់ឡាន',4,null),
('Houses','ផ្ទះ',5,null),
('Lands','ដី',5,null),
('Jewelry & Watches','គ្រឿងអលង្ការ និង នាឡិកា',6,null),
('Clothing & Accessories','សម្លៀកបំពាក់ និង គ្រឿងលំអរ',6,null),
('Beauty & Healthcare','គ្រឿងសំអាង និង សុខភាព',6,null),
('Books','គ្រឿងសង្ហារឹម និង ដេគ័រ',7,null),
('Sports Equipment','ឧបករណ៍កីឡា',7,null),
('CDS,DVDS,VHS','CDS,DVDS,VHS',7,null),
('Household Items','សម្ភារៈក្នុងផ្ទះ',8,null),
('Office Furniture','សម្ភារៈក្នុងការិយាល័យ',8,null),
('Home Furniture','គ្រឿងសង្ហារឹមក្នុងផ្ទះ',8,null),
('Kitchenware','សម្ភារៈក្នុងផ្ទះបាយ',8,null),
('Handicrafts Paintings','សិប្បកម្ម និងគំនូរ',8,null);